Vexcenot/-Middle-Mann

resource/ui/scoreboard.res
gets rid of the white line normally used in the scoreboard in non-mvm gamemodes
=> 2nd minor mvm fix

#customizations/Last Damage Position/Above Player Model (Default)/resource/ui/huddamageaccount.res, #customizations/Last Damage Position/Below Crosshair/resource/ui/huddamageaccount.res
added 2 options for people who want to revert to default + made last damage on centered crosshair yellow
=> reworked last damage customization

resource/ui/flagstatus.res, resource/ui/mvmbombcarrierprogresspanel.res
=> (some) mvm fixes

scripts/hudanimations_VEXCENOT'S centered default.txt
closes #30, hopefully i don't have to open this one again
=> fixed medic lags when hitting multiple enemies with shield

resource/ui/freezepanel_basic.res, resource/ui/hudinspectpanel.res, resource/ui/spectator.res
1080p+ fix
reported by selbi on gamebanana: https://gamebanana.com/posts/11027508
=> fixed black bars on warpainted weapons

resource/ui/classloadoutpanel.res, resource/ui/econ/backpackpanel.res, resource/ui/freezepanel_basic.res, resource/ui/hudinspectpanel.res, resource/ui/itemselectionpanel.res, resource/ui/spectator.res
and everywhere else that applies, too.
closes #46
=> increased quality of images in backpack

resource/ui/huditemeffectmeter_demoman.res
my original method broke on 16:9, this should be fine.
=> fixed background on demoman meter

resource/ui/HudDemomanPipes.res, resource/ui/huditemeffectmeter_demoman.res
=> more fixes to demo meters

resource/ui/hudmannvsmachinestatus.res, resource/ui/hudobjectiveflagpanel.res
fixes #72 by just moving the mvm bomb carrier status stuff down by around 5-ish pixels
=> lowered mvm bomb stuff slightly down

.gitattributes
aka: whenever downloading, there will be no extra files.
=> improvements to gitattributes file

#customizations/Health&Ammo Positions/Centered (Default)/scripts/hudlayout.res, resource/ui/HudDemomanPipes.res, scripts/hudlayout.res
=> fixed health and demo stickies being offcenter

resource/ui/HudDemomanPipes.res
self-descriptive
addendum to #77
=> made demo sticky icon appear regardless of stickies

resource/ui/spectatorguihealth.res
=> made targetid cross less jarring to look at

#customizations/Health Warning/Off (Default)/resource/ui/hudplayerhealth.res, #customizations/Health Warning/On/resource/ui/hudplayerhealth.res, #customizations/Health Warning/Overwatch style screen overlay/resource/ui/hudplayerhealth.res, #customizations/Health&Ammo Positions/Centered (Default)/resource/ui/hudplayerhealth.res, resource/ui/hudplayerhealth.res
=> moved all status effect icons next to the player model instead of above

resource/ui/hudpasstimeballstatus.res
=> made pass time hud bar smaller

#customizations/Health&Ammo Positions/Centered (Default)/scripts/hudlayout.res, #customizations/Health&Ammo Positions/TF2 Style (Corners)/scripts/hudlayout.res, .gitignore, scripts/hudlayout.res
=> fixed arena mode stuff

scripts/hudanimations_VEXCENOT'S centered default.txt
=> removed overriding DamagedPlayer Animations messing with in-built crosshairs

resource/ui/mainmenuoverride.res
who cares im not making another whole update for this shit
=> updated store for smissmas

materials/vgui/replay/thumbnails/ico_crit.vmt, materials/vgui/replay/thumbnails/ico_crit_blu.vmt, resource/ui/custom/preload.res
=> fix crit icon not preloading again

resource/ui/objectivestatusescort.res
- Should fix #110 
Tested on:
* ~2560x1440
* Linux
=> Fix cart alert border

.github/ISSUE_TEMPLATE/bug-report.md, resource/ui/mainmenuoverride.res, resource/ui/spectator.res
=> fix #126 + some safe measures for better bug reporting
